language: python
python: '3.6'

cache:
 directories:
  - $HOME/virtualenv

install:
 - pip install -r requirements.txt
 - pip install coveralls[yaml] nose-cov
 - python setup.py install --force

script:
 - nosetests -v --with-xunit --with-coverage --cover-inclusive --cover-branches --cover-package catch

after_success:
 - coveralls
