language: python
sudo: false

cache:
 directories:
  - $HOME/virtualenv

python:
  - '3.7'

install:
 - pip install -r requirements.txt
 - pip install coveralls[yaml] nose-cov
 - python setup.py install --force

script:
 - nosetests -v --with-xunit --with-coverage --cover-inclusive --cover-branches --cover-package catch

after_success:
 - coveralls
